version: 0.2
phases: 
  install:
    runtime-versions:
        docker: 18     
    
  pre_build: 
    
  build: 
    commands: 
    
    # update the following line with the name of your own ECR repository
    -docker build -t $866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest:latest .
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag orangehrm:latest 866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest

  post_build: 
    commands: 
  
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    -  docker push 866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest

    

