version: 0.2
phases: 
  install:
    runtime-versions:
        docker: 18     
    commands: 
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      
  pre_build: 
    commands: 
         #REPOSITORY_URI=123456789.dkr.ecr.eu-866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latestwest-1.amazonaws.com/sample/sampleapp 
  build: 
    commands: 
    
    # update the following line with the name of your own ECR repository
    -docker build -t $866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest:latest .
    # update the following line with the URI of your own ECR repository (view the Push Commands in the console)
    - docker tag orangehrm:latest 866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest

  post_build: 
    commands: 
  
    - echo pushing to repo
    # update the following line with the URI of your own ECR repository
    -  docker push 866453577062.dkr.ecr.ap-south-1.amazonaws.com/orangehrm:latest

    
   
artifacts:
  files:
    - imageDetail.json
